In [1]:
import pandas as pd
import numpy as np        # what's actually in that folder

In [2]:
df= pd.read_csv("../data/loans.csv")
df.head()

,customer.id,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,10001,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854.0,52.1,0.0,0,0,0
1,10002,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623.0,76.7,0.0,0,0,0
2,10003,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511.0,25.6,1.0,0,0,0
3,10004,1,debt_consolidation,0.1008,162.34,11.350407,8.1,712,2699.958333,33667.0,73.2,1.0,0,0,0
4,10005,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740.0,39.5,0.0,1,0,0

In [3]:
print(df.shape)

(9578, 15)

In [5]:
print(df.dtypes)

customer.id            int64
credit.policy            str
purpose                  str
int.rate             float64
installment          float64
log.annual.inc       float64
dti                      str
fico                   int64
days.with.cr.line    float64
revol.bal            float64
revol.util               str
inq.last.6mths       float64
delinq.2yrs              str
pub.rec                  str
not.fully.paid         int64
dtype: object

In [6]:
print(df.isnull().sum())

customer.id           0
credit.policy         0
purpose               0
int.rate              0
installment           0
log.annual.inc        5
dti                   0
fico                  0
days.with.cr.line    29
revol.bal             1
revol.util           62
inq.last.6mths       30
delinq.2yrs          29
pub.rec              29
not.fully.paid        0
dtype: int64

In [8]:
df.describe()

,customer.id,int.rate,installment,log.annual.inc,fico,days.with.cr.line,revol.bal,inq.last.6mths,not.fully.paid
count,9578.000000,9578.000000,9578.000000,9573.000000,9578.000000,9549.000000,9.577000e+03,9548.000000,9578.000000
mean,14789.500000,0.125529,319.089413,10.931892,711.159532,4562.026085,1.691529e+04,1.571743,0.160054
std,2765.074773,0.202225,207.071301,0.614766,42.024737,2497.985733,3.375770e+04,2.198151,0.366676
min,10001.000000,0.060000,15.670000,7.547502,612.000000,178.958333,0.000000e+00,0.000000,0.000000
25%,12395.250000,0.103900,163.770000,10.558414,682.000000,2820.000000,3.187000e+03,0.000000,0.000000
50%,14789.500000,0.122100,268.950000,10.928238,707.000000,4139.958333,8.596000e+03,1.000000,0.000000
75%,17183.750000,0.140700,432.762500,11.289832,737.000000,5730.000000,1.825200e+04,2.000000,0.000000
max,19578.000000,14.700000,940.140000,14.528354,1812.000000,17639.958330,1.207359e+06,33.000000,1.000000

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['customer.id'].drop_duplicates

<bound method Series.drop_duplicates of 0       10001
1       10002
2       10003
3       10004
4       10005
        ...
9573    19574
9574    19575
9575    19576
9576    19577
9577    19578
Name: customer.id, Length: 9578, dtype: int64>

In [14]:
df[df['days.with.cr.line'].isna() | df['delinq.2yrs'].isna() | df['pub.rec'].isna()]

,customer.id,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
7725,17726,0,all_other,0.0775,156.11,11.156251,8.81,772,NaN,0.0,NaN,NaN,NaN,NaN,0
7726,17727,0,all_other,0.0838,204.84,NaN,4,742,NaN,0.0,NaN,NaN,NaN,NaN,0
7727,17728,0,all_other,0.0807,136.45,11.695247,4,742,NaN,0.0,NaN,NaN,NaN,NaN,0
7728,17729,0,all_other,0.0933,80.69,11.608236,10,712,NaN,0.0,NaN,NaN,NaN,NaN,0
7729,17730,0,all_other,0.0933,124.62,11.492723,10,707,NaN,0.0,NaN,NaN,NaN,NaN,0
7731,17732,0,all_other,0.1028,164.42,11.461632,10,702,NaN,0.0,NaN,NaN,NaN,NaN,0
7732,17733,0,all_other,0.0964,32.11,9.392662,10,697,NaN,0.0,NaN,NaN,NaN,NaN,0
7733,17734,0,all_other,0.0996,103.20,11.918391,10,692,NaN,0.0,NaN,NaN,NaN,NaN,0
7734,17735,0,all_other,0.1028,113.39,12.100712,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0
7735,17736,0,all_other,0.1122,211.85,10.373491,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0
7736,17737,0,all_other,0.0964,208.66,9.903488,10,712,NaN,0.0,NaN,NaN,NaN,NaN,1
7737,17738,0,all_other,0.0996,64.50,8.699515,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0
7738,17739,0,all_other,0.1249,42.65,10.596635,10,707,NaN,0.0,NaN,NaN,NaN,NaN,1
7739,17740,0,all_other,0.0933,95.86,9.903488,10,712,NaN,0.0,NaN,NaN,NaN,NaN,0
7740,17741,0,all_other,0.0901,95.42,10.463103,10,717,NaN,0.0,NaN,NaN,NaN,NaN,0
7741,17742,0,all_other,0.0775,209.18,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0
7742,17743,0,all_other,0.0775,218.55,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0
7743,17744,0,all_other,0.0743,155.38,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0
7744,17745,0,all_other,0.1122,344.87,11.002100,19.5,742,NaN,0.0,NaN,NaN,NaN,NaN,0
7745,17746,0,all_other,0.0712,30.94,10.819778,1.1,772,NaN,0.0,NaN,NaN,NaN,NaN,0
7746,17747,0,all_other,0.0838,81.94,8.779557,6.46,722,NaN,0.0,NaN,NaN,NaN,NaN,1
7747,17748,0,all_other,0.0743,93.23,11.289782,0.39,797,NaN,0.0,NaN,NaN,NaN,NaN,0
7748,17749,0,all_other,0.0743,77.69,11.106820,10.36,787,NaN,0.0,NaN,NaN,NaN,NaN,0
7749,17750,0,all_other,0.0775,156.11,12.611538,5.38,757,NaN,0.0,NaN,NaN,NaN,NaN,0
7750,17751,0,all_other,0.1407,34.21,10.126631,16.27,642,NaN,0.0,NaN,NaN,NaN,NaN,0
7751,17752,0,all_other,0.1091,45.78,10.596635,8.61,672,NaN,0.0,NaN,NaN,NaN,NaN,0
7752,17753,0,all_other,0.1122,164.23,10.239960,3.51,672,NaN,0.0,NaN,NaN,NaN,NaN,0
7753,17754,0,all_other,0.0901,38.17,10.491274,3.27,707,NaN,0.0,NaN,NaN,NaN,NaN,0
7758,17759,0,debt_consolidation,0.0964,61.00,11.512925,10,707,NaN,0.0,NaN,NaN,NaN,NaN,0

In [15]:
df[df['days.with.cr.line'].isna()]['credit.policy'].value_counts()

credit.policy
0    29
Name: count, dtype: int64

In [16]:
df[df['log.annual.inc'].isna()]
df[df['revol.bal'].isna()]

,customer.id,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
1004,11005,1,debt_consolidation,0.1008,193.83,10.778956,9.3,707,6329.958333,NaN,36.2,0.0,0,0,1

In [17]:
df[df['log.annual.inc'].isna()]

,customer.id,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
1010,11011,1,home_improvement,0.1071,116.56,NaN,13.3,702,6060.0,10083.0,53.9,1.0,0,1,1
7726,17727,0,all_other,0.0838,204.84,NaN,4,742,NaN,0.0,NaN,NaN,NaN,NaN,0
7741,17742,0,all_other,0.0775,209.18,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0
7742,17743,0,all_other,0.0775,218.55,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0
7743,17744,0,all_other,0.0743,155.38,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0

In [18]:
df[df['fico'] > 850]

,customer.id,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
110,10111,1,credit_card,0.1059,235.96,10.950807,7.22,1712,5519.0,40598.0,77.3,1.0,0,0,0
174,10175,1,home_improvement,0.0712,92.80,11.440355,0,1812,8250.0,368.0,1.2,0.0,0,0,0
565,10566,1,debt_consolidation,0.1703,535.02,11.580584,15.81,1662,6660.0,44543.0,86.8,0.0,0,0,1

In [19]:
df[df['int.rate'] > 1]

,customer.id,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
170,10171,1,all_other,14.70,51.78,10.126631,3.84,632,1530.0,1238.0,61.9,1.0,1,0,0
801,10802,1,debt_consolidation,13.25,118.34,10.950807,23.05,687,2730.0,45988.0,88.4,0.0,0,0,0

In [41]:
df=pd.read_csv('../data/loans.csv')

In [42]:
df.loc[df['fico'] > 850, 'fico'] = df.loc[df['fico'] > 850, 'fico'] - 1000

In [43]:
df.loc[df['int.rate'] > 1, 'int.rate'] = df.loc[df['int.rate'] > 1, 'int.rate'] / 100

In [48]:
df['fico'].describe()

count    9578.000000
mean      710.846314
std        37.970537
min       612.000000
25%       682.000000
50%       707.000000
75%       737.000000
max       827.000000
Name: fico, dtype: float64

In [47]:
df['int.rate'].describe()

count    9578.000000
mean        0.122640
std         0.026847
min         0.060000
25%         0.103900
50%         0.122100
75%         0.140700
max         0.216400
Name: int.rate, dtype: float64

In [49]:
purpose_dummies = pd.get_dummies(df['purpose'], prefix='purpose', drop_first=True).astype(int)
df = pd.concat([df, purpose_dummies], axis=1)
df = df.drop(columns=['purpose'])

In [50]:
df.dtypes

customer.id                     int64
credit.policy                     str
int.rate                      float64
installment                   float64
log.annual.inc                float64
dti                               str
fico                            int64
days.with.cr.line             float64
revol.bal                     float64
revol.util                        str
inq.last.6mths                float64
delinq.2yrs                       str
pub.rec                           str
not.fully.paid                  int64
purpose_credit_card             int64
purpose_debt_consolidation      int64
purpose_educational             int64
purpose_home_improvement        int64
purpose_major_purchase          int64
purpose_small_business          int64
dtype: object

In [51]:
df['dti'].value_counts()

dti
0        89
10       19
0.6      16
12       13
15.1     13
         ..
3.23      1
24.41     1
10.31     1
23.74     1
24.05     1
Name: count, Length: 2530, dtype: int64

In [52]:
pd.to_numeric(df['dti'], errors='coerce').isna().sum()

np.int64(1)

In [53]:
df[pd.to_numeric(df['dti'], errors='coerce').isna()]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
1927,11928,1,0.1379,170.38,10.714418,six,722,5280.041667,0.0,NaN,1.0,0,0,0,0,0,0,0,0,0

In [58]:
df['dti']= df['dti'].replace("six",6)

In [65]:
df['dti']=pd.to_numeric(df['dti'])

In [66]:
df['dti'].dtype

dtype('float64')

In [54]:
df[pd.to_numeric(df['credit.policy'], errors='coerce').isna()]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
2668,12669,one,0.1632,529.71,11.082143,16.39,672,5310.000000,7467.0,48.8,2.0,0,0,0,0,0,0,0,0,0
9567,19568,zero,0.1311,101.24,10.968198,8.23,687,2790.041667,1514.0,13.8,5.0,0,0,0,0,0,0,0,0,0

In [67]:
df['credit.policy']= df['credit.policy'].replace('one',1)
df['credit.policy']= df['credit.policy'].replace('zero',0)

In [68]:
df['credit.policy'].dtype

dtype('O')

In [69]:
df['credit.policy']=pd.to_numeric(df['credit.policy'])

In [70]:
df['credit.policy'].dtype

dtype('int64')

In [55]:
df[pd.to_numeric(df['revol.util'], errors='coerce').isna()]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
781,10782,1,0.1134,98.70,10.530495,7.72,677,1680.000000,0.0,NaN,1.0,0,0,1,0,0,0,0,0,0
803,10804,1,0.1103,52.41,10.532096,15.84,682,1829.958333,0.0,NaN,0.0,0,0,0,0,0,1,0,0,0
839,10840,1,0.1134,263.20,10.714418,8.75,682,2490.000000,0.0,NaN,1.0,1,0,1,0,1,0,0,0,0
857,10858,1,0.1229,23.35,9.852194,12.38,662,1199.958333,0.0,NaN,1.0,0,0,0,0,1,0,0,0,0
1213,11214,1,0.1064,182.39,11.264464,4.26,697,4140.958333,0.0,NaN,0.0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8570,18571,0,0.1387,163.75,10.736397,22.72,662,2010.000000,0.0,NaN,6.0,0,0,0,0,1,0,0,0,0
8676,18677,0,0.0976,128.62,10.752484,7.29,707,990.000000,0.0,NaN,0.0,0,0,0,0,0,0,0,1,0
8759,18760,0,0.0863,170.80,10.680516,10.18,742,2399.958333,0.0,NaN,3.0,0,0,0,1,0,0,0,0,0
9073,19074,0,0.1442,859.57,12.542545,5.58,737,7890.000000,290291.0,NaN,1.0,0,0,0,0,0,0,0,0,0
9364,19365,0,0.1774,172.91,9.546813,9.51,692,1530.041667,0.0,NaN,4.0,0,0,0,0,1,0,0,0,0

In [71]:
mask = df['revol.util'].notna() & pd.to_numeric(df['revol.util'], errors='coerce').isna()
df[mask]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
1883,11884,1,0.0768,77.98,10.373491,0.38,822,9968.041667,510.0,one,0.0,0,0,1,0,1,0,0,0,0

In [72]:
df['revol.util']=df['revol.util'].replace('one',1)
df['revol.util']= pd.to_numeric(df['revol.util'])
df['revol.util'].dtype

dtype('float64')

In [56]:
df[pd.to_numeric(df['delinq.2yrs'], errors='coerce').isna()]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
245,10246,1,0.1091,304.90,11.163684,18.96,692,5430.0,5749.0,43.2,1.0,yes,0,0,0,1,0,0,0,0
7725,17726,0,0.0775,156.11,11.156251,8.81,772,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7726,17727,0,0.0838,204.84,NaN,4,742,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7727,17728,0,0.0807,136.45,11.695247,4,742,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7728,17729,0,0.0933,80.69,11.608236,10,712,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7729,17730,0,0.0933,124.62,11.492723,10,707,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7731,17732,0,0.1028,164.42,11.461632,10,702,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7732,17733,0,0.0964,32.11,9.392662,10,697,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7733,17734,0,0.0996,103.20,11.918391,10,692,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7734,17735,0,0.1028,113.39,12.100712,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7735,17736,0,0.1122,211.85,10.373491,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7736,17737,0,0.0964,208.66,9.903488,10,712,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0
7737,17738,0,0.0996,64.50,8.699515,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7738,17739,0,0.1249,42.65,10.596635,10,707,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0
7739,17740,0,0.0933,95.86,9.903488,10,712,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7740,17741,0,0.0901,95.42,10.463103,10,717,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7741,17742,0,0.0775,209.18,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7742,17743,0,0.0775,218.55,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7743,17744,0,0.0743,155.38,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7744,17745,0,0.1122,344.87,11.002100,19.5,742,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7745,17746,0,0.0712,30.94,10.819778,1.1,772,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7746,17747,0,0.0838,81.94,8.779557,6.46,722,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0
7747,17748,0,0.0743,93.23,11.289782,0.39,797,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7748,17749,0,0.0743,77.69,11.106820,10.36,787,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7749,17750,0,0.0775,156.11,12.611538,5.38,757,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7750,17751,0,0.1407,34.21,10.126631,16.27,642,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7751,17752,0,0.1091,45.78,10.596635,8.61,672,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7752,17753,0,0.1122,164.23,10.239960,3.51,672,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7753,17754,0,0.0901,38.17,10.491274,3.27,707,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7758,17759,0,0.0964,61.00,11.512925,10,707,NaN,0.0,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0

In [73]:
mask = df['delinq.2yrs'].notna() & pd.to_numeric(df['delinq.2yrs'], errors='coerce').isna()
df[mask]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
245,10246,1,0.1091,304.9,11.163684,18.96,692,5430.0,5749.0,43.2,1.0,yes,0,0,0,1,0,0,0,0

In [74]:
df['delinq.2yrs'] = df['delinq.2yrs'].replace('yes', 1)
df['delinq.2yrs'] = pd.to_numeric(df['delinq.2yrs'])
print(df['delinq.2yrs'].dtype)

float64

In [57]:
df[pd.to_numeric(df['pub.rec'], errors='coerce').isna()]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
236,10237,1,0.1280,554.37,11.034890,19.22,677,3060.041667,17641.0,69.5,2.0,0,no,0,0,1,0,0,0,0
7725,17726,0,0.0775,156.11,11.156251,8.81,772,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7726,17727,0,0.0838,204.84,NaN,4,742,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7727,17728,0,0.0807,136.45,11.695247,4,742,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7728,17729,0,0.0933,80.69,11.608236,10,712,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7729,17730,0,0.0933,124.62,11.492723,10,707,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7731,17732,0,0.1028,164.42,11.461632,10,702,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7732,17733,0,0.0964,32.11,9.392662,10,697,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7733,17734,0,0.0996,103.20,11.918391,10,692,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7734,17735,0,0.1028,113.39,12.100712,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7735,17736,0,0.1122,211.85,10.373491,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7736,17737,0,0.0964,208.66,9.903488,10,712,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0
7737,17738,0,0.0996,64.50,8.699515,10,687,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7738,17739,0,0.1249,42.65,10.596635,10,707,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0
7739,17740,0,0.0933,95.86,9.903488,10,712,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7740,17741,0,0.0901,95.42,10.463103,10,717,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7741,17742,0,0.0775,209.18,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7742,17743,0,0.0775,218.55,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7743,17744,0,0.0743,155.38,NaN,1,802,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7744,17745,0,0.1122,344.87,11.002100,19.5,742,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7745,17746,0,0.0712,30.94,10.819778,1.1,772,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7746,17747,0,0.0838,81.94,8.779557,6.46,722,NaN,0.0,NaN,NaN,NaN,NaN,1,0,0,0,0,0,0
7747,17748,0,0.0743,93.23,11.289782,0.39,797,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7748,17749,0,0.0743,77.69,11.106820,10.36,787,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7749,17750,0,0.0775,156.11,12.611538,5.38,757,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7750,17751,0,0.1407,34.21,10.126631,16.27,642,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7751,17752,0,0.1091,45.78,10.596635,8.61,672,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7752,17753,0,0.1122,164.23,10.239960,3.51,672,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7753,17754,0,0.0901,38.17,10.491274,3.27,707,NaN,0.0,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0
7758,17759,0,0.0964,61.00,11.512925,10,707,NaN,0.0,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0

In [75]:
mask = df['pub.rec'].notna() & pd.to_numeric(df['pub.rec'], errors='coerce').isna()
df[mask]

,customer.id,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
236,10237,1,0.128,554.37,11.03489,19.22,677,3060.041667,17641.0,69.5,2.0,0.0,no,0,0,1,0,0,0,0

In [76]:
df['pub.rec'] = df['pub.rec'].replace('no', 0)
df['pub.rec'] = pd.to_numeric(df['pub.rec'])
print(df['pub.rec'].dtype)

float64

In [77]:
df.dtypes

customer.id                     int64
credit.policy                   int64
int.rate                      float64
installment                   float64
log.annual.inc                float64
dti                           float64
fico                            int64
days.with.cr.line             float64
revol.bal                     float64
revol.util                    float64
inq.last.6mths                float64
delinq.2yrs                   float64
pub.rec                       float64
not.fully.paid                  int64
purpose_credit_card             int64
purpose_debt_consolidation      int64
purpose_educational             int64
purpose_home_improvement        int64
purpose_major_purchase          int64
purpose_small_business          int64
dtype: object

In [78]:
df = df.drop(columns=['int.rate', 'credit.policy'])
df.columns

Index(['customer.id', 'installment', 'log.annual.inc', 'dti', 'fico',
       'days.with.cr.line', 'revol.bal', 'revol.util', 'inq.last.6mths',
       'delinq.2yrs', 'pub.rec', 'not.fully.paid', 'purpose_credit_card',
       'purpose_debt_consolidation', 'purpose_educational',
       'purpose_home_improvement', 'purpose_major_purchase',
       'purpose_small_business'],
      dtype='str')

In [81]:
df = df.drop(columns=['installment'])

In [82]:
df.columns

Index(['log.annual.inc', 'dti', 'fico', 'days.with.cr.line', 'revol.bal',
       'revol.util', 'inq.last.6mths', 'delinq.2yrs', 'pub.rec',
       'not.fully.paid', 'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement',
       'purpose_major_purchase', 'purpose_small_business'],
      dtype='str')

In [83]:
df['revol.bal_to_income']= df['revol.bal']/np.exp(df['log.annual.inc'])
df['revol.bal_to_income'].describe()

count    9572.000000
mean        0.235474
std         0.269675
min         0.000000
25%         0.062348
50%         0.164630
75%         0.317987
max         3.654631
Name: revol.bal_to_income, dtype: float64

In [84]:
df['years_with_cr_line']= (df['days.with.cr.line'])/365
df['years_with_cr_line'].describe()

count    9549.000000
mean       12.498702
std         6.843797
min         0.490297
25%         7.726027
50%        11.342352
75%        15.698630
max        48.328653
Name: years_with_cr_line, dtype: float64

In [85]:
df = df.drop(columns=['days.with.cr.line'])
df.columns

Index(['log.annual.inc', 'dti', 'fico', 'revol.bal', 'revol.util',
       'inq.last.6mths', 'delinq.2yrs', 'pub.rec', 'not.fully.paid',
       'purpose_credit_card', 'purpose_debt_consolidation',
       'purpose_educational', 'purpose_home_improvement',
       'purpose_major_purchase', 'purpose_small_business',
       'revol.bal_to_income', 'years_with_cr_line'],
      dtype='str')

In [86]:
df.columns
df.shape

(9578, 17)

In [87]:
df.to_csv("../data/loans_cleaned.csv", index=False)